### ISSUE TITLE
How to reproduce results from other datasets in the paper?

### ISSUE THREAD

**Issue by Ryhhhh** [ChaejeongLee/CoDi#1]
I have successfully replicated the results with the initial dataset provided, but I would like to achieve the results for the other datasets in the paper.

Upon reviewing the repository’s documentation and issues, I was unable to locate the specific JSON and NPZ files for these datasets. These files are essential for accurately replicating the results and comparing them with the findings presented in the paper.

Could you please make these files available and please let me know if there are any usage restrictions or guidelines that I need to be aware of when using these datasets?

**Comment by ChaejeongLee** [comment]
I've added Python files for making .npz and .json files in 'tabular_datasets/make_heart.py'. 
By running this file, you can easily create input data using .csv files. 

Thank you!

**Comment by Ryhhhh** [comment]
> I've added Python files for making .npz and .json files in 'tabular_datasets/make_heart.py'. By running this file, you can easily create input data using .csv files.
> 
> Thank you!

Thanks for your help.
